/****************************************************************
-- DROP TABLE SA_CORP;
-- DROP TABLE SA_CTRY;
****************************************************************/
CREATE TABLE SA_CTRY
(
	CTRYID				INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '국가일련번호',
	CTRY_CODE          	VARCHAR(32) COMMENT '국가코드',
	CTRY_NAME			VARCHAR(700) COMMENT '국가명',
	AUTH_USERID      	INT COMMENT '작성자일련번호',
	AUTH_NAME        	VARCHAR (700) COMMENT '작성자이름',
	AUTH_DISP        	VARCHAR (700) COMMENT '작성자상세이름',
	RGST_USERID			INT COMMENT '등록자일련번호',
	RGST_NAME			VARCHAR (700) COMMENT '등록자이름',
	RGST_DISP        	VARCHAR (700) COMMENT '등록자상세이름',
	INST_DATE       	DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '입력일시',
	LAST_UPDT       	DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '마지막수정일시',
	TENANTID           	INT COMMENT '회사별ID',
	ISUSE				TINYINT DEFAULT 0 NOT NULL COMMENT '사용여부'
) COMMENT = '국가';

CREATE TABLE SA_CORP
(
	CORPID				INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '법인일련번호',
	CTRYID				INT COMMENT '국가일련번호',
	CORP_TYPE			INT COMMENT '점포구분코드',
	CORP_NAME			VARCHAR (700) COMMENT '법인명',
	DESCR				VARCHAR (2000) COMMENT '설명',
	STATUS				SMALLINT DEFAULT -1 NOT NULL COMMENT '상태',
	ISVISB				TINYINT DEFAULT 0 NOT NULL COMMENT '보임여부',
	AUTH_USERID			INT COMMENT '작성자일련번호',
	AUTH_NAME			VARCHAR (700) COMMENT '작성자이름',
	AUTH_DISP			VARCHAR (700) COMMENT '작성자상세이름',
	RGST_USERID			INT COMMENT '등록자일련번호',
	RGST_NAME			VARCHAR (700) COMMENT '등록자이름',
	RGST_DISP			VARCHAR (700) COMMENT '등록자상세이름',
	RGST_DATE			DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
	LAST_UPDT			DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '마지막수정일시',
	ACT_USERID			INT COMMENT '대표담당자일련번호',
	ACT_NAME			VARCHAR (700) COMMENT '대표담당자이름',
	ACT_DISP			VARCHAR (700) COMMENT '대표담당자상세이름',
	ACT_CNT				INT DEFAULT 0 COMMENT '담당자수',
	TENANTID			INT COMMENT '회사별ID'
) COMMENT = '법인(점) 관리';

ALTER TABLE SA_CORP ADD
	CONSTRAINT SACTRY_R_SACORP FOREIGN KEY (CTRYID)
	REFERENCES SA_CTRY(CTRYID);

CREATE UNIQUE INDEX XIE_SACTRY_CTRYCODE ON SA_CTRY
(
	CTRY_CODE ASC
);

CREATE INDEX XIE_SACTRY_CTRYNAME ON SA_CTRY
(
	CTRY_NAME ASC
);

CREATE INDEX XIE_SACORP_CORPNAME ON SA_CORP 
(
	CORP_NAME ASC
);

CREATE INDEX XIE_SACORP_CORPTYPE ON SA_CORP
(
	CORP_TYPE ASC
);